version: "3"

services: 
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8085:8081

  backend:
    container_name: backend
    build: ./backend
    restart: always
    links:
      - mongo
    volumes:
      - ./backend:/workspace/api
    ports:
      - "3001:3001"
    command: npm run dev

  #fontend:
  #  container_name: react
  #  build: ./frontend
  #  restart: always
  #  links:
  #    - backend
  #  volumes:
  #    - ./frontend:/workspace/api
  #  ports:
  #    - "3000:3000"
  #  command: yarn start
